plugins:
  onlyoffice_connector_enabled:
    default: true
    client: true

  ONLYOFFICE_Docs_address:
    default: 'http://localhost'
    client: true
  ONLYOFFICE_Docs_secret_key:
    default: ''
    client: true
  JWT_header:
    default: 'Authorization'
    client: true
  ONLYOFFICE_Docs_address_for_internal_requests_from_the_server:
    default: 'http://localhost'
  Server_address_for_internal_requests_from_ONLYOFFICE_Docs:
    default: 'http://localhost'
    client: true
  ONLYOFFICE_connector_auto_authorize_extensions:
    default: true
  Connect_to_demo_ONLYOFFICE_Docs_server:
    default: false
    client: true